# Generated by Django 3.1.5 on 2021-01-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210127_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='plan',
            name='timevalue',
            field=models.CharField(default='2021', max_length=5),
            preserve_default=False,
        ),
    ]
