# Generated by Django 3.1.5 on 2021-01-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210128_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('-', 'note'), ('○', 'event'), ('·', 'todo')], default='·', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('>', 'migrate'), ('<', 'planned'), ('x', 'done')], max_length=5, null=True),
        ),
    ]
