# Generated by Django 3.1.5 on 2021-01-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210128_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='timevalue',
            field=models.CharField(max_length=10),
        ),
    ]
