# Generated by Django 3.1.5 on 2021-01-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210128_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='type',
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('-', 'note'), ('○', 'event'), ('·', 'todo'), ('>', 'migrate'), ('<', 'planned'), ('x', 'done')], default='·', max_length=5),
        ),
    ]
