# Generated by Django 3.1.5 on 2021-01-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210128_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('-', 'note'), ('∘', 'event'), ('·', 'todo'), ('>', 'migrate'), ('<', 'planned'), ('x', 'done')], default='·', max_length=5),
        ),
    ]
